      - name: Generate components.json
        run: |
          # Start JSON array
          echo "[" > components.json
          
          # Collect JSON objects in a variable (to handle commas properly)
          JSON_OBJECTS=()

          for file in components/*.jsx components/*.tsx; do
            [ -e "$file" ] || continue
            
            name=$(basename "$file" | sed 's/\..*$//')
            definition_file="components/$name.definition.json"

            description=""

            if [ -f "$definition_file" ]; then
              echo "Found definition file: $definition_file"
              description=$(jq -r '.description // empty' "$definition_file" | awk '{$1=$1};1')  # Trim spaces/newlines

              if [ -z "$description" ]; then
                echo "Warning: No description found in $definition_file"
              else
                echo "Extracted description: $description"
              fi
            else
              echo "No definition file for $name"
            fi

            # Ensure proper JSON escaping
            description=$(echo "$description" | jq -R '.')

            JSON_OBJECTS+=("{ \"name\": \"$name\", \"source\": \"https://raw.githubusercontent.com/mdings/studio-components/main/$file\", \"description\": $description }")
          done
          
          # Join JSON objects with a comma and output correctly
          (IFS=,; echo "${JSON_OBJECTS[*]}") >> components.json
          
          # Close JSON array
          echo "]" >> components.json
