name: Update Components Manifest
on:
  push:
    branches:
      - main

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate components.json
        run: |
          # Start JSON array
          echo "[" > components.json
          
          # Collect JSON objects in a variable (to handle commas properly)
          JSON_OBJECTS=()

          for file in components/*.jsx components/*.tsx; do
            [ -e "$file" ] || continue
            
            name=$(basename "$file" | sed 's/\..*$//')
            definition_file="components/$name.definition.json"

            description=""

            if [ -f "$definition_file" ]; then
              echo "Found definition file: $definition_file"
              description=$(jq -r '.description // empty' "$definition_file")

              if [ -z "$description" ]; then
                echo "Warning: No description found in $definition_file"
              else
                echo "Extracted description: $description"
              fi
            else
              echo "No definition file for $name"
            fi

            # Escape double quotes in description
            description=$(echo "$description" | jq -R -s '. | @json')

            JSON_OBJECTS+=("{ \"name\": \"$name\", \"source\": \"https://raw.githubusercontent.com/mdings/studio-components/main/$file\", \"description\": $description }")
          done
          
          # Join JSON objects with a comma and output correctly
          (IFS=,; echo "${JSON_OBJECTS[*]}") >> components.json
          
          # Close JSON array
          echo "]" >> components.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add components.json
          git commit -m "Auto-update components.json with descriptions" || exit 0
          git push origin main
