name: Update Components Manifest
on:
  push:
    branches:
      - main

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} # 🔥 Use the stored PAT

      - name: Generate components.json
        run: |
          # Start JSON array
          echo "[" > components.json
          
          # Collect JSON objects in a variable (to handle commas properly)
          JSON_OBJECTS=()
          
          for file in components/*.jsx components/*.tsx; do
            [ -e "$file" ] || continue
            name=$(basename "$file" .jsx | basename "$file" .tsx)
            JSON_OBJECTS+=("{ \"name\": \"$name\", \"source\": \"https://raw.githubusercontent.com/mdings/studio-components/main/$file\" }")
          done
          
          # Join JSON objects with a comma and output correctly
          (IFS=,; echo "${JSON_OBJECTS[*]}") >> components.json
          
          # Close JSON array
          echo "]" >> components.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add components.json
          git commit -m "Auto-update components.json" || exit 0
          git push origin main
